name: Bot Notify PR is Merged on beta-release branch

on:
  pull_request:
    types: [closed]
    branches:
      - beta-release

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Github Action To Telegram
        uses: gsi-dayronrafael/telewire@telebot
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          status: ${{ job.status }}
