
name: Bot will notify PR is merged

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Github Action To Telegram
        uses: gsi-dayronrafael/telewire@master
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          status: ${{ job.status }}
